# #####################################################################
# Automatically generated by qmake (2.01a) Sat Aug 18 20:44:49 2012
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += . \
    images
INCLUDEPATH += . \
    images

# Input
HEADERS += lzwdialog.h \
    lzw.h
FORMS += lzwdialog.ui
SOURCES += lzwdialog.cpp \
    main.cpp \
    lzw.cpp
RESOURCES += resource.qrc
